version: '3'

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
        user: 1000
        uid: 1000
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - network-aula

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - .docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
        - network-aula

  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_PASSWORD: "root"
      MYSQL_USER: "bruno"
      MYSQL_DATABASE: "aula"
    networks:
      - network-aula

networks:
  network-aula:
    driver: bridge
