version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: 1000
        uid: 1000
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_PASSWORD: "root"
      MYSQL_USER: "bruno"
      MYSQL_DATABASE: "aula"